### ISSUE TITLE
Add Done Job - Done Button Error

### ISSUE THREAD

**Issue by trannguyen1510** [bichu136/Planning-App#20]
Khi bấm start của timer (và bấm pause lẫn không bấm pause) sau đó nhấn done thì báo lỗi

**Comment by bichu136** [comment]
cho bk lỗi nó báo gì đi

**Comment by trannguyen1510** [comment]
Bị null ở chỗ cusor.UpdateByDoing(...) trong Button_Done_Click

**Comment by bichu136** [comment]
chọn đủ các công việc hết rồi??

**Comment by bichu136** [comment]
tại ông chưa chọn công việc á.
tui check hết trường hợp òi

**Comment by trannguyen1510** [comment]
Check mai đem cho ông xem cho ông xem
