### ISSUE TITLE
Hoàn thành bản UI (mockup) đầy đủ

### ISSUE THREAD

**Issue by trannguyen1510** [bichu136/Planning-App#6]
- Liệt kê các bản UI cần thiết
- Phân công công việc cho từng thành viên
- Dealine: trước chiều CN tuần này (29/09/19)
P.S. làm hình ảnh thôi, không cần tương tác, và bỏ vào folder UI

**Comment by bichu136** [comment]
đã cho vào file img rồi đó, mọi người vào đó xem ha.
Có ai muốn giúp thiết kế cái UI đó nữa thì lên discord vào channel design form chat ha
trong hình những nơi có: 
+màu vàng là đang làm, 
+màu xanh lá là xong,
+màu đỏ là đang cần tìm người làm hộ
